name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev build-essential git autoconf automake \
            libtool libffi-dev cmake libssl-dev libltdl-dev openjdk-11-jdk zip unzip

      - name: Install Buildozer
        run: pip install buildozer

      - name: Accept Android SDK licenses
        run: |
          # Создаём папку для SDK и принимаем лицензии
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p $ANDROID_SDK_ROOT
          cd $ANDROID_SDK_ROOT
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip
          yes | ./cmdline-tools/bin/sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT

      - name: Build APK
        run: |
          export BUILDOZER_ALLOW_ROOT=1
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: jawtracker-apk
          path: bin/*.apk
